import AppKit
import Carbon
import OverboardCore

/// Polls NSPasteboard.changeCount and emits plain-struct snapshots.
/// All privacy gating happens here, before any pasteboard data is read.
public final class ClipboardMonitor {
    /// Written alongside paste-back payloads so the monitor never re-captures
    /// its own writes.
    public static let markerType = NSPasteboard.PasteboardType("com.nickysemenza.overboard.internal")

    public nonisolated static let defaultExclusions: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "org.keepassxc.keepassxc",
    ]

    /// Pasteboard types the monitor refuses to capture — privacy flavors plus
    /// our own paste-back marker. Internal so tests can pin the invariant that
    /// PastebackService tags writes with a type this set actually skips.
    static let skippedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.SensitiveType"),
        NSPasteboard.PasteboardType("com.apple.is-sensitive"),
        markerType,
    ]

    struct CaptureLimits: Sendable {
        var maxSnapshotBytes = 64 * 1024 * 1024
        var maxRepresentationBytes = 50 * 1024 * 1024
        var maxItemCount = 64
        var maxFlavorsPerItem = 32
        var maxRepresentationCount = 256
    }

    public let snapshots: AsyncStream<PasteboardSnapshot>
    private let continuation: AsyncStream<PasteboardSnapshot>.Continuation
    private var timer: Timer?
    private var admission = CaptureAdmission()
    private var lastChangeCount: Int
    private let pasteboard: NSPasteboard
    private let captureLimits: CaptureLimits
    private let secureInputEnabled: () -> Bool
    private let sourceApplication: () -> (bundleID: String?, name: String?)

    /// Evaluated on every capture so Settings changes apply immediately.
    public var excludedBundleIDs: () -> Set<String> = { ClipboardMonitor.defaultExclusions }

    public convenience init() {
        self.init(
            pasteboard: .general,
            secureInputEnabled: { IsSecureEventInputEnabled() },
            sourceApplication: {
                let application = NSWorkspace.shared.frontmostApplication
                return (application?.bundleIdentifier, application?.localizedName)
            }
        )
    }

    init(
        pasteboard: NSPasteboard,
        bufferCapacity: Int = 8,
        captureLimits: CaptureLimits = .init(),
        secureInputEnabled: @escaping () -> Bool = { false },
        sourceApplication: @escaping () -> (bundleID: String?, name: String?) = { (nil, nil) }
    ) {
        self.pasteboard = pasteboard
        self.captureLimits = captureLimits
        self.secureInputEnabled = secureInputEnabled
        self.sourceApplication = sourceApplication
        self.lastChangeCount = pasteboard.changeCount
        (self.snapshots, self.continuation) = AsyncStream.makeStream(
            of: PasteboardSnapshot.self,
            bufferingPolicy: .bufferingNewest(min(8, max(1, bufferCapacity)))
        )
    }

    public func start() {
        guard timer == nil else { return }
        self.admission.invalidate()
        self.admission = CaptureAdmission()
        self.lastChangeCount = self.pasteboard.changeCount
        // 200 ms: imperceptible capture latency, negligible CPU. .common mode
        // so capture keeps working while menus are tracked.
        let timer = Timer(timeInterval: 0.2, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        self.admission.invalidate()
        self.timer?.invalidate()
        self.timer = nil
    }

    private func tick() {
        self.flushPendingCapture()
    }

    @discardableResult
    public func flushPendingCapture() -> Bool {
        guard let snapshot = self.capturePendingSnapshot() else { return false }
        self.continuation.yield(snapshot)
        return true
    }

    public func capturePendingSnapshot() -> PasteboardSnapshot? {
        guard (try? self.admission.check()) != nil else { return nil }
        let pasteboard = self.pasteboard
        let changeCount = pasteboard.changeCount
        // Polling reads only the pasteboard's *current* contents. If several
        // copies land within one interval, changeCount jumps by more than one
        // and the intermediate clips are never seen — an accepted tradeoff of a
        // changeCount poll (macOS has no general pasteboard-change callback);
        // shorten the timer interval if the gap matters more than idle CPU.
        guard changeCount != self.lastChangeCount else { return nil }
        self.lastChangeCount = changeCount

        guard let snapshot = readSnapshot(from: pasteboard), pasteboard.changeCount == changeCount else { return nil }
        return snapshot
    }

    private func readSnapshot(from pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        let items = pasteboard.pasteboardItems ?? []
        let boardTypes = pasteboard.types ?? []
        guard items.count <= self.captureLimits.maxItemCount,
              boardTypes.count <= self.captureLimits.maxRepresentationCount else { return nil }
        var representationCount = 0
        var types = Set(boardTypes)
        for item in items {
            guard item.types.count <= self.captureLimits.maxFlavorsPerItem,
                  item.types.count <= self.captureLimits.maxRepresentationCount - representationCount
            else { return nil }
            representationCount += item.types.count
            types.formUnion(item.types)
        }

        // Privacy gates — checked before reading any payload.
        if Self.skippedTypes.contains(where: types.contains) {
            return nil
        }
        if self.secureInputEnabled() {
            return nil
        }

        let source = self.sourceApplication()
        if let bundleID = source.bundleID, self.excludedBundleIDs().contains(bundleID) {
            return nil
        }

        var reps: [PasteboardSnapshot.Rep] = []
        var totalBytes = 0
        for (index, item) in items.enumerated() {
            guard let itemReps = self.representations(from: item, itemIndex: index, totalBytes: &totalBytes)
            else { return nil }
            reps.append(contentsOf: itemReps)
        }
        guard !reps.isEmpty else { return nil }

        return PasteboardSnapshot(
            reps: reps,
            sourceBundleID: source.bundleID,
            sourceAppName: source.name,
            admission: self.admission
        )
    }

    private func representations(
        from item: NSPasteboardItem, itemIndex: Int, totalBytes: inout Int
    ) -> [PasteboardSnapshot.Rep]? {
        var reps: [PasteboardSnapshot.Rep] = []
        for type in item.types where !Self.skippedTypes.contains(type) {
            guard let rawData = item.data(forType: type) else { continue }
            guard rawData.count <= self.captureLimits.maxRepresentationBytes,
                  rawData.count <= self.captureLimits.maxSnapshotBytes - totalBytes else { return nil }
            let data: Data
            let uti: String
            if type == .fileURL {
                guard let urlString = String(data: rawData, encoding: .utf8), URL(string: urlString)?.isFileURL == true,
                      let encoded = try? JSONEncoder().encode([urlString])
                else { continue }
                data = encoded
                uti = WellKnownUTI.fileURLs
            } else {
                data = rawData
                uti = type.rawValue
            }
            guard data.count <= self.captureLimits.maxRepresentationBytes,
                  data.count <= self.captureLimits.maxSnapshotBytes - totalBytes else { return nil }
            totalBytes += data.count
            reps.append(.init(uti: uti, data: data, itemIndex: itemIndex))
        }
        return reps
    }
}
