import AppKit
import Carbon
import OverboardCore

/// Polls NSPasteboard.changeCount and emits plain-struct snapshots.
/// All privacy gating happens here, before any pasteboard data is read.
public final class ClipboardMonitor {
    /// Written alongside paste-back payloads so the monitor never re-captures
    /// its own writes.
    public static let markerType = NSPasteboard.PasteboardType("com.nickysemenza.overboard.internal")

    public nonisolated static let defaultExclusions: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "org.keepassxc.keepassxc",
    ]

    /// Pasteboard types the monitor refuses to capture — privacy flavors plus
    /// our own paste-back marker. Internal so tests can pin the invariant that
    /// PastebackService tags writes with a type this set actually skips.
    static let skippedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        markerType,
    ]

    /// Single representation payloads above this are dropped (the rest of the
    /// snapshot is still captured).
    private static let maxRepBytes = 50 * 1024 * 1024

    public let snapshots: AsyncStream<PasteboardSnapshot>
    private let continuation: AsyncStream<PasteboardSnapshot>.Continuation
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Evaluated on every capture so Settings changes apply immediately.
    public var excludedBundleIDs: () -> Set<String> = { ClipboardMonitor.defaultExclusions }

    public init() {
        self.lastChangeCount = NSPasteboard.general.changeCount
        (self.snapshots, self.continuation) = AsyncStream.makeStream(of: PasteboardSnapshot.self)
    }

    public func start() {
        guard timer == nil else { return }
        self.lastChangeCount = NSPasteboard.general.changeCount
        // 200 ms: imperceptible capture latency, negligible CPU. .common mode
        // so capture keeps working while menus are tracked.
        let timer = Timer(timeInterval: 0.2, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        self.timer?.invalidate()
        self.timer = nil
    }

    private func tick() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        // Polling reads only the pasteboard's *current* contents. If several
        // copies land within one interval, changeCount jumps by more than one
        // and the intermediate clips are never seen — an accepted tradeoff of a
        // changeCount poll (macOS has no general pasteboard-change callback);
        // shorten the timer interval if the gap matters more than idle CPU.
        guard changeCount != self.lastChangeCount else { return }
        self.lastChangeCount = changeCount

        guard let snapshot = readSnapshot(from: pasteboard) else { return }
        self.continuation.yield(snapshot)
    }

    private func readSnapshot(from pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        let types = pasteboard.types ?? []

        // Privacy gates — checked before reading any payload.
        if Self.skippedTypes.contains(where: types.contains) {
            return nil
        }
        if IsSecureEventInputEnabled() {
            return nil
        }

        let frontmost = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontmost?.bundleIdentifier, self.excludedBundleIDs().contains(bundleID) {
            return nil
        }

        // Each representation kind is classified independently so this method
        // stays a flat dispatch table instead of one long branchy function.
        let repExtractors: [(NSPasteboard) -> PasteboardSnapshot.Rep?] = [
            self.fileURLRep(from:),
            self.imageRep(from:),
            self.colorRep(from:),
            self.rtfRep(from:),
            self.htmlRep(from:),
            self.plainTextRep(from:),
        ]
        let reps = repExtractors.compactMap { $0(pasteboard) }
        guard !reps.isEmpty else { return nil }

        return PasteboardSnapshot(
            reps: reps,
            sourceBundleID: frontmost?.bundleIdentifier,
            sourceAppName: frontmost?.localizedName
        )
    }

    private func fileURLRep(from pasteboard: NSPasteboard) -> PasteboardSnapshot.Rep? {
        guard let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty else { return nil }
        guard let data = try? JSONEncoder().encode(urls.map(\.absoluteString)) else { return nil }
        return .init(uti: WellKnownUTI.fileURLs, data: data)
    }

    private func imageRep(from pasteboard: NSPasteboard) -> PasteboardSnapshot.Rep? {
        if let png = capped(pasteboard.data(forType: .png)) {
            return .init(uti: WellKnownUTI.png, data: png)
        }
        // TIFF pasteboard data is enormous; store PNG instead.
        guard let tiff = capped(pasteboard.data(forType: .tiff)),
              let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
        else { return nil }
        return .init(uti: WellKnownUTI.png, data: png)
    }

    private func colorRep(from pasteboard: NSPasteboard) -> PasteboardSnapshot.Rep? {
        let colorType = NSPasteboard.PasteboardType(WellKnownUTI.color)
        guard pasteboard.types?.contains(colorType) == true,
              let data = capped(pasteboard.data(forType: colorType))
        else { return nil }
        return .init(uti: WellKnownUTI.color, data: data)
    }

    private func rtfRep(from pasteboard: NSPasteboard) -> PasteboardSnapshot.Rep? {
        guard let rtf = capped(pasteboard.data(forType: .rtf)) else { return nil }
        return .init(uti: WellKnownUTI.rtf, data: rtf)
    }

    private func htmlRep(from pasteboard: NSPasteboard) -> PasteboardSnapshot.Rep? {
        guard let html = capped(pasteboard.data(forType: .html)) else { return nil }
        return .init(uti: WellKnownUTI.html, data: html)
    }

    private func plainTextRep(from pasteboard: NSPasteboard) -> PasteboardSnapshot.Rep? {
        guard let string = pasteboard.string(forType: .string),
              let data = capped(string.data(using: .utf8))
        else { return nil }
        return .init(uti: WellKnownUTI.plainText, data: data)
    }

    private func capped(_ data: Data?) -> Data? {
        guard let data, data.count <= Self.maxRepBytes else { return nil }
        return data
    }
}
