import AppKit
import Carbon
import os
import OverboardCore

/// Polls NSPasteboard.changeCount and emits plain-struct snapshots.
/// All privacy gating happens here, before any pasteboard data is read.
@MainActor
public final class ClipboardMonitor {
    /// Written alongside paste-back payloads so the monitor never re-captures
    /// its own writes.
    public static let markerType = NSPasteboard.PasteboardType("com.nicky.overboard.internal")

    public nonisolated static let defaultExclusions: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "org.keepassxc.keepassxc",
    ]

    private static let skippedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        markerType,
    ]

    /// Single representation payloads above this are dropped (the rest of the
    /// snapshot is still captured).
    private static let maxRepBytes = 50 * 1024 * 1024

    public let snapshots: AsyncStream<PasteboardSnapshot>
    private let continuation: AsyncStream<PasteboardSnapshot>.Continuation
    private var timer: Timer?
    private var lastChangeCount: Int
    private let logger = Logger(subsystem: "com.nicky.overboard", category: "monitor")

    /// Evaluated on every capture so Settings changes apply immediately.
    public var excludedBundleIDs: () -> Set<String> = { ClipboardMonitor.defaultExclusions }

    public init() {
        self.lastChangeCount = NSPasteboard.general.changeCount
        (self.snapshots, self.continuation) = AsyncStream.makeStream(of: PasteboardSnapshot.self)
    }

    public func start() {
        guard timer == nil else { return }
        self.lastChangeCount = NSPasteboard.general.changeCount
        // 200 ms: imperceptible capture latency, negligible CPU. .common mode
        // so capture keeps working while menus are tracked.
        let timer = Timer(timeInterval: 0.2, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        self.timer?.invalidate()
        self.timer = nil
    }

    private func tick() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != self.lastChangeCount else { return }
        self.lastChangeCount = changeCount

        guard let snapshot = readSnapshot(from: pasteboard) else { return }
        self.continuation.yield(snapshot)
    }

    private func readSnapshot(from pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        let types = pasteboard.types ?? []

        // Privacy gates — checked before reading any payload.
        if Self.skippedTypes.contains(where: types.contains) { return nil }
        if IsSecureEventInputEnabled() { return nil }

        let frontmost = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontmost?.bundleIdentifier, self.excludedBundleIDs().contains(bundleID) {
            return nil
        }

        var reps: [PasteboardSnapshot.Rep] = []

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            if let data = try? JSONEncoder().encode(urls.map(\.absoluteString)) {
                reps.append(.init(uti: WellKnownUTI.fileURLs, data: data))
            }
        }

        if let png = capped(pasteboard.data(forType: .png)) {
            reps.append(.init(uti: WellKnownUTI.png, data: png))
        } else if let tiff = capped(pasteboard.data(forType: .tiff)) {
            // TIFF pasteboard data is enormous; store PNG instead.
            if let png = NSBitmapImageRep(data: tiff)?
                .representation(using: .png, properties: [:])
            {
                reps.append(.init(uti: WellKnownUTI.png, data: png))
            }
        }

        let colorType = NSPasteboard.PasteboardType(WellKnownUTI.color)
        if types.contains(colorType), let data = capped(pasteboard.data(forType: colorType)) {
            reps.append(.init(uti: WellKnownUTI.color, data: data))
        }

        if let rtf = capped(pasteboard.data(forType: .rtf)) {
            reps.append(.init(uti: WellKnownUTI.rtf, data: rtf))
        }
        if let html = capped(pasteboard.data(forType: .html)) {
            reps.append(.init(uti: WellKnownUTI.html, data: html))
        }
        if let string = pasteboard.string(forType: .string),
           let data = capped(string.data(using: .utf8))
        {
            reps.append(.init(uti: WellKnownUTI.plainText, data: data))
        }

        guard !reps.isEmpty else { return nil }

        return PasteboardSnapshot(
            reps: reps,
            sourceBundleID: frontmost?.bundleIdentifier,
            sourceAppName: frontmost?.localizedName
        )
    }

    private func capped(_ data: Data?) -> Data? {
        guard let data, data.count <= Self.maxRepBytes else { return nil }
        return data
    }
}
